### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by d4l3k** [techx/hackmit-hackify#6]
Hey!

I'm one of the developers working on the [nwHacks](https://nwhacks.io) hackathon. I'd love to be able to use a modified copy of Hackify for our hackathon!

However, I've noticed that this project doesn't have a license mentioned in the README or a LICENSE file so the legality of us using it is questionable. (Our fork is at https://github.com/nwhacks/hackify).

Could you guys add a LICENSE so we can use it?

Thanks!

**Comment by anishathalye** [comment]
Thanks for respecting copyright law! :smile:

@andrewilyas - you're the author, so you hold the copyright. Could you release this under the MIT license (as we do with almost all our software)?

**Comment by andrewilyas** [comment]
Added! Hackify is now licensed under the MIT license.

**Comment by d4l3k** [comment]
Thank you so much!
